version: "3.0"
services:
  firebase-emulator:
    build: .
    image: firebase-emulator:firebase-emulator
    volumes:
      - .:/app
    ports:
      - 8001:8001
      - 4000:4000
      - 4400:4400
      - 4500:4500
      - 5000:5000
      - 5001:5001
      - 8080:8080
      - 9000:9000
      - 9005:9005
    command: firebase emulators:start
    # command: /bin/sh -c 'while :; do sleep 6h; done;'